site_name: SSM Middleware Doc
site_url: null

nav:
  - Introduction : 'index.md'
  - Getting Started: 'GettingStarted/GettingStarted.md'
  - 'How to call API': 
        - 'Token Authentication': 'How To Call API/Token Authentication/tokenAuthentication.md'
        - 'WSDL File': 
            - 'Sample Request': 'How To Call API/WSDL File/sampleRequest.md'
            - 'Sample Respond': 'How To Call API/WSDL File/sampleResponse.md'
  - 'Profile Webservice': 
        - 'getInfoProfile': 'Profile Webservice/getInfoProfile/getInfoProfile.md'
        - 'getCompProfile': 'Profile Webservice/getCompProfile/getCompProfile.md' 
        - 'getBizProfile': 'Profile Webservice/getBizProfile/getBizProfile.md'
        - 'getNewFormatEntityNo.': 'Profile Webservice/getNewFormatEntityNo/getNewFormatEntityNo.md'
        - 'Sample Report':
            - 'ROB': 'Profile Webservice/Data Mapping/ROB/DataMappingROB.md'
            - 'ROC': 'Profile Webservice/Sample Report/ROC/SampleReportROC.md'
        - 'Data Mapping' :
            - 'ROB': 'Profile Webservice/Data Mapping/ROC/DataMappingROC.md'
            - 'ROC': 'Profile Webservice/Data Mapping/ROB/DataMappingROB.md'
            - 'LLP': 'Profile Webservice/Data Mapping/LLP/DataMappingLLP.md' 
  - 'Data Schema':
        - 'ROB': 'Data Schema/DataSchemaROB.md'
        - 'ROC': 'Data Schema/DataSchemaROC.md'
  - 'PDF': 'PDF/pdf.md' 
theme:
    # name: windmill-dark
    name: mkdocs



extra_css:
    - css/extra.css


plugins:
    - search

markdown_extensions:
    - toc:
        permalink: "#"