site_name: SSM Middleware Doc

nav:
  - 'Intro' : 
        - 'Introduction' : 'index.md'
        - 'Getting Started': 'Documents/GettingStarted/GettingStarted.md'
        - 'How to call API': 
            - 'Token Authentication': 'Documents/How To Call API/Token Authentication/tokenAuthentication.md'
            - 'WSDL File': 'Documents/How To Call API/WSDL File/WSDL_File.md'
  - 'Profile Webservice': 
        - 'getInfoProfile': 
            - 'ROCINFO': 'Documents/Profile Webservice/getInfoProfile/getInfoProfileROC.md'
            - 'ROBINFO': 'Documents/Profile Webservice/getInfoProfile/getInfoProfileROB.md'
        - 'getCompProfile': 'Documents/Profile Webservice/getCompProfile/getCompProfile.md' 
        - 'getBizProfile': 'Documents/Profile Webservice/getBizProfile/getBizProfile.md'
        - 'getNewFormatEntityNo.': 'Documents/Profile Webservice/getNewFormatEntityNo/getNewFormatEntityNo.md'
        - 'Sample Report':
            - 'ROB': 'Documents/Profile Webservice/Sample Report/ROB/SampleReportROB.md'
            - 'ROC': 'Documents/Profile Webservice/Sample Report/ROC/SampleReportROC.md'
        - 'Data Mapping' :
            - 'ROB': 'Documents/Profile Webservice/Data Mapping/ROB/DataMappingROB.md'
            - 'ROC': 'Documents/Profile Webservice/Data Mapping/ROC/DataMappingROC.md'
            - 'LLP': 'Documents/Profile Webservice/Data Mapping/LLP/DataMappingLLP.md' 
        - Error: 'Documents/Profile Webservice/ErrorMessage/ErrorMessage.md'
  - 'Data Schema':
        - 'ROB': 'Documents/Data Schema/DataSchemaROB.md'
        - 'ROC': 'Documents/Data Schema/DataSchemaROC.md'
  - 'Development': 'Documents/Data Schema/testing.md'

theme:
    name: material
    font:
        text: Helvetica
    features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.sections
    - toc.integrate
    - content.code.annotate # 
    - content.tabs.link

    favicon: img/favicon.png
    logo: img/logo.png

    palette: # 
     - scheme: default
       primary: light blue
       accent: yellow
       toggle:
        icon: material/eye-outline
        name: Switch to dark mode 
     - scheme: slate # 
       primary: light blue
       accent: yellow
       toggle:
        icon: material/eye
        name: Switch to light mode

extra_css:
    - stylesheets/extra.css
    - https://unpkg.com/mermaid@7.1.2/dist/mermaid.css

extra_javascript:
    - https://unpkg.com/mermaid@7.1.2/dist/mermaid.min.js

plugins:
    - search

markdown_extensions:
    - toc:
        permalink: "#"
    - attr_list
    - md_in_html
    - pymdownx.highlight
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences:
        custom_fences:
            - name: mermaid
              class: mermaid
            #   format: !!python/name:pymdownx.superfences.fence_code_format
              format: !!python/name:pymdownx.superfences.fence_div_format
    - pymdownx.tabbed:
        alternate_style: true 
