site_name: SSM Middleware Doc
site_url: null

nav:
  - 'Menu' : 
        - 'Introduction' : 'index.md'
        - 'Getting Started': 'Documents/GettingStarted/GettingStarted.md'
        - 'How to call API': 
            - 'Token Authentication': 'Documents/How To Call API/Token Authentication/tokenAuthentication.md'
            - 'WSDL File': 'Documents/How To Call API/WSDL File/WSDL_File.md'

#   - Introduction : 'index.md'
#   - Getting Started: 'Documents/GettingStarted/GettingStarted.md'
#   - 'How to call API': 
#         - 'Token Authentication': 'Documents/How To Call API/Token Authentication/tokenAuthentication.md'
#         - 'WSDL File': 'Documents/How To Call API/WSDL File/WSDL_File.md'

  - 'Profile Webservice': 
        - 'getInfoProfile': 
            - 'ROCINFO': 'Documents/Profile Webservice/getInfoProfile/getInfoProfileROC.md'
            - 'ROBINFO': 'Documents/Profile Webservice/getInfoProfile/getInfoProfileROB.md'
        - 'getCompProfile': 'Documents/Profile Webservice/getCompProfile/getCompProfile.md' 
        - 'getBizProfile': 'Documents/Profile Webservice/getBizProfile/getBizProfile.md'
        - 'getNewFormatEntityNo.': 'Documents/Profile Webservice/getNewFormatEntityNo/getNewFormatEntityNo.md'
        - 'Sample Report':
            - 'ROB': 'Documents/Profile Webservice/Sample Report/ROB/SampleReportROB.md'
            - 'ROC': 'Documents/Profile Webservice/Sample Report/ROC/SampleReportROC.md'
        - 'Data Mapping' :
            - 'ROB': 'Documents/Profile Webservice/Data Mapping/ROB/DataMappingROB.md'
            - 'ROC': 'Documents/Profile Webservice/Data Mapping/ROC/DataMappingROC.md'
            - 'LLP': 'Documents/Profile Webservice/Data Mapping/LLP/DataMappingLLP.md' 
  - 'Data Schema':
        - 'ROB': 'Documents/Data Schema/DataSchemaROB.md'
        - 'ROC': 'Documents/Data Schema/DataSchemaROC.md'

theme:
    # name: windmill-dark
    name: mkdocs
    # name: readthedocs



extra_css:
    - css/extra.css


plugins:
    - search

markdown_extensions:
    - toc:
        permalink: "#"